### ISSUE TITLE
Pathway analysis of the results from H-MAGMA

### ISSUE THREAD

**Issue by zqsha** [thewonlab/H-MAGMA#1]
Hi thewonlab,

Thank you for developing such an amazing toolbox. Recently, I am using H-MAGMA to do my research and it's very user-friendly. I just have a quick question. Can I use the output (e.g. adult_brain.genes.raw) to run the gene-set analysis using MAGMA? I found in the output, the genes were named after ENSG (e.g. ENSG00000230368). For most of the gene-set files of MsigDB, they use symbols (e.g. XRN2) and entrez (e.g. 2205) to name genes. So, when I run gene-set analysis using adult_brain.genes.raw, it could not be recognized by the gene-set files of MsigDB. Do you have any suggestions? 

Thank you so much. I really appreciate. Looking forward to your reply.

Best,
Zhiqiang

**Comment by hyejungwon** [comment]
Hi Zhiqiang,

Sorry for the late reply. I guess you might have already figured things out by now, but you can use biomaRt (https://bioconductor.org/packages/release/bioc/html/biomaRt.html) to convert ENSG to entrez IDs or hgnc.

**Comment by zqsha** [comment]
Yes, I have figured it out. Thanks for your reply :)
