### ISSUE TITLE
Missing LDSC annot files

### ISSUE THREAD

**Issue by fleurg** [thewonlab/H-MAGMA#3]
Dear thewonlab, @seynancy 
Thanks so much for providing the H-MAGMA toolbox. 
Keen to run the LDSC however, we ran into parsing problems. 
It seems the annot files are missing for chr 16, 17, 18, 19, 2, 20, 21, 22, 3, 4, 5.
Hoping you can check on this,
Thanks again for your help, 
Many kind regards, 
Fleur

**Comment by seynancy** [comment]
Hi Fleur,
Thanks for bring this to our attention. The annot files mentioned have been uploaded.
Best,
Nancy
