### ISSUE TITLE
MAGMA using singularity?

### ISSUE THREAD

**Issue by clagiamba** [thewonlab/H-MAGMA#6]
Thank you for the software and code! 

I am using a computer cluster and I have problems installing the software with the following error messages:
./magma: /u/local/compilers/gcc/4.9.3/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./magma)./magma: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./magma)

Do you happen to have a solution for this?
Do you maybe have a singularity version of MAGMA?

Thank you

**Comment by hyejungwon** [comment]
Hi @clagiamba 

This is something we cannot control, because we are not the original developer of MAGMA. Can you check with Christiaan (https://ctg.cncr.nl/software/magma)?

**Comment by clagiamba** [comment]
Yes sure, thank you for the link.
