### ISSUE TITLE
MAGMA for high coverage WGS data

### ISSUE THREAD

**Issue by Shicheng-Guo** [thewonlab/H-MAGMA#7]
It looks MAGMA will receive some errors when running for high coverage WGS data. I am wondering is there any non-biased approach to pre-processing the data so that MAGMA could be applied for high coverage WGS data? 

Thanks. 
Shicheng

**Comment by hyejungwon** [comment]
Hi @Shicheng-Guo, 

Yes, that should be possible! We now compiled the code to generate H-MAGMA input files of your choice. Please check out `/Codes/H-MAGMA_annotation_generation.rmd`. You can change the SNP information (`snps <- read.table("EUR.bim")`) into the variant list you have from WGS data.
