### ISSUE TITLE
Output files for 9 brain disorders

### ISSUE THREAD

**Issue by malosreet** [thewonlab/H-MAGMA#8]
Hello, 

I was wondering where to find the H-MAGMA output files for the 9 brain disorders for which GWAS data was used in this paper: https://www.nature.com/articles/s41593-020-0603-0

Thank you for your help!

**Comment by seynancy** [comment]
Hi there,
It seems the output files folder was accidentally deleted. We have restored the file so you should be able to view output files for the 9 brain disorders. Thanks for using our tool!
